services:
  db:
    image: postgres:16
    container_name: p_db_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: p_user
      POSTGRES_PASSWORD: p_pass
      POSTGRES_DB: P_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
