FROM node:20-alpine

WORKDIR /app

# Copiamos los archivos de configuración de dependencias
COPY package*.json ./

# Instalamos las dependencias
RUN npm install

# Copiamos el resto del código del frontend
COPY . .

# Exponemos el puerto estándar donde corre React (Vite suele usar 5173, CRA usa 3000)
EXPOSE 5173

# Comando para iniciar en modo desarrollo
CMD ["npm", "run", "dev"]